---
sudo: required
services: docker
addons:
  apt:
    packages:
    - docker-ce
language: ruby
matrix:
  include:
  - env: ELASTIC_STACK_VERSION=5.6.9
  - env: ELASTIC_STACK_VERSION=6.5.4
  - env: ELASTIC_STACK_VERSION=7.0.0-alpha2
  fast_finish: true
install: true
script: ci/unit/docker-test.sh
before_install: gem install bundler -v '< 2'
